#?????
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scorems?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations:
    - classpath*:/mapper/*.xml
  type-aliases-package: artwork.entity.User.User

token:
  secretKey: lab^@#@78*&^os

server:
  port: 8080